#
# E01-AIO Automacao Ltda. ME.
# Autor: Nelio Santos (nelio@e01aio.com.br)
#
# Configurações gerais do zshrc com oh-my-zsh

# Save history
HISTFILE=$HOME/.zsh_history
HISTSIZE=10000
SAVEHIST=10000
setopt appendhistory

# configure oh-my-zsh
export ZSH="$HOME/.oh-my-zsh"
ZSH_THEME="robbyrussell"
ZSH_DISABLE_COMPFIX="true"
DISABLE_UPDATE_PROMPT=true
DISABLE_AUTO_UPDATE="true"
ENABLE_CORRECTION="false"
COMPLETION_WAITING_DOTS="true"
HIST_STAMPS="yyyy-mm-dd"
plugins=(git npm ansible brew docker nvm zsh-interactive-cd history-substring-search zsh-autosuggestions)
source $ZSH/oh-my-zsh.sh

if [ ! -f $HOME/.notmux ] && [ "x$TMUX" = "x" ] ; then
    tmux new-session -A -s main
fi

setopt auto_cd

export VISUAL=vi
export EDITOR=$VISUAL

#
# Scripts personalizados
#
export PATH="/usr/local/bin:/usr/local/sbin:$PATH:$HOME/.zshcustoms/scripts"

if [ -d $HOME/.local/bin ] ; then
    export PATH="$PATH:$HOME/.local/bin"
fi

if [ -d $HOME/.yarn ] ; then
    export PATH="$PATH:$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin"
fi

if [ -d $HOME/.deno ] ; then
    export PATH="$PATH:$HOME/.deno/bin"
fi

if [ -d $HOME/.cargo/bin ] ; then
    export PATH="$PATH:$HOME/.cargo/bin"
fi

if [ -d $HOME/.platformio/penv/bin ] ; then
    export PATH="$PATH:$HOME/.platformio/penv/bin"
fi

#
# Personalizações por sistema operacional
#
if [ "$OSTYPE" = "linux-gnueabihf" ] || [ "$OSTYPE" = "linux-gnu" ]; then
    source ~/.zshcustoms/linux/zshrc
fi

if [ "$OSTYPE" = "darwin17.0" -o "$OSTYPE" = "darwin18.0" -o "$OSTYPE" = "darwin19.0" -o "$OSTYPE" = "darwin20.0" -o "$OSTYPE" = "darwin21.0" ] ; then
    source ~/.zshcustoms/macos/zshrc
fi

source ~/.zshcustoms/general/aliases

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
if [ -f ~/.zshlocal ] ; then
    source ~/.zshlocal
fi

# function nvm_start() {
#     unfunction "$0"
#     export NVM_DIR="$HOME/.nvm"
#     [ -s "/usr/local/opt/nvm/nvm.sh" ] && \. "/usr/local/opt/nvm/nvm.sh"  # This loads nvm
#     [ -s "/usr/local/opt/nvm/etc/bash_completion.d/nvm" ] && \. "/usr/local/opt/nvm/etc/bash_completion.d/nvm"  # This loads nvm bash_completion
# }

function help() {
    if [ -f /usr/local/bin/mdless ] ; then
        mdless --no-pager ~/.zshcustoms/motd.md
    fi
}

eval "$(starship init zsh)"
