#
# E01-AIO Automacao Ltda. ME.
# Autor: Nelio Santos (nelio@e01aio.com.br)
# Data: 2017-02-14
#

if [ -f "/etc/kubernetes/admin.conf" ] ; then
    export KUBECONFIG="/etc/kubernetes/admin.conf"
fi

if [ -d /usr/local/go ] ; then
    export GOROOT="/usr/local/go"
    export GOPATH="/usr/local"
    export PATH="$PATH:$GOROOT/bin"
fi

#
# Alguns atalhos importantes
#
alias netmon_type="netstat -atn | awk '/tcp/ {print $6}' | sort | uniq -c"
alias netmon_timewait="ss -neopt state time-wait | wc -l"
alias netmon_established="ss -neopt state established | wc -l"
alias netmon_stats="nstat -a"

alias tm="tail -f /var/log/messages"
alias tsyslog="tail -f /var/log/syslog"
alias iftop="TERM=vt100 iftop"

# Adiciona neovim como editor padrão.
if [ -d /usr/local/nvim-linux64 ] ; then
    alias vi="/usr/local/nvim-linux64/bin/nvim"
    alias vim="/usr/local/nvim-linux64/bin/nvim"
    export VISUAL="/usr/local/nvim-linux64/bin/nvim"
    export EDITOR="/usr/local/nvim-linux64/bin/nvim"
fi

if [ -x /usr/local/bin/nvim ] ; then
    alias vi="/usr/local/bin/nvim"
    alias vim="/usr/local/bin/nvim"
    export VISUAL="/usr/local/bin/nvim"
    export EDITOR="/usr/local/bin/nvim"
fi
